
// ESP32
// GND -> GND POWER SUPPLY
// 5V -> 5V POWER SUPPLY

// 8x32 WS2812E LED MATRIX
// GND -> GND POWER SUPPLY
// POWER -> 5V POWER SUPPLY
// DATA IN -> ESP32

// DM996 SERVO MOTOR
// GND -> GND POWER SUPPLY
// POWER -> 5V POWER SUPPLY
// DATA IN -> ESP32

// SPEAKER 5 W - 8 OHM - 2.54 MM DUPONT
// SPK1 -> MP3-TF-16P
// SPK2 -> MP3-TF-16P

// MP3-TF-16P
// VCC -> 5V POWER SUPPLY
// RX -> ESP32
// TX -> ESP32
// SPK1 -> SPEAKER
// GND -> GND POWER SUPPLY
// SPK2 -> SPEAKER
